@startuml
'https://plantuml.com/class-diagram

interface Strategy {
    + {abstract} show()
}
class StrategyA
StrategyA .up.|> Strategy
class StrategyB
StrategyB .up.|> Strategy
class StrategyC
StrategyC .up.|> Strategy

class SalesMan {
    - strategy: Strategy
    + setStrategy(strategy: Strategy): void
    + salesManShow(): void
}

Strategy -right-o SalesMan
@enduml